### ISSUE TITLE
clicking edit link of id errors out

### ISSUE THREAD

**Issue by MichaelVoth** [jejcode/madlibs#42]
Cannot read properties of undefined. reading "title"

**Comment by MichaelVoth** [comment]
Looks like it is making a put request instead of a get request.

index-8c2dbd70.js:73     PUT http://18.117.159.214/api/templates/64c0a7af0c9d196644374740/edit 400 (Bad Request)
(anonymous) @ index-8c2dbd70.js:73
xhr @ index-8c2dbd70.js:73
Sf @ index-8c2dbd70.js:73
request @ index-8c2dbd70.js:73
(anonymous) @ index-8c2dbd70.js:73
(anonymous) @ index-8c2dbd70.js:71
pS @ index-8c2dbd70.js:73
(anonymous) @ index-8c2dbd70.js:73
(anonymous) @ index-8c2dbd70.js:73
Ji @ index-8c2dbd70.js:40
Xn @ index-8c2dbd70.js:40
bg @ index-8c2dbd70.js:40
sn @ index-8c2dbd70.js:40
Mc @ index-8c2dbd70.js:40
en @ index-8c2dbd70.js:38
(anonymous) @ index-8c2dbd70.js:40
index-8c2dbd70.js:40 TypeError: Cannot read properties of undefined (reading 'title')
    at hS (index-8c2dbd70.js:73:15705)
    at Qa (index-8c2dbd70.js:38:19479)
    at Bl (index-8c2dbd70.js:40:3134)
    at Pp (index-8c2dbd70.js:40:44559)
    at Tp (index-8c2dbd70.js:40:39572)
    at Vg (index-8c2dbd70.js:40:39500)
    at Pi (index-8c2dbd70.js:40:39355)
    at Ql (index-8c2dbd70.js:40:35752)
    at Rp (index-8c2dbd70.js:40:34708)
    at C (index-8c2dbd70.js:25:1562)
overrideMethod @ console.js:213
Ml @ index-8c2dbd70.js:40
n.callback @ index-8c2dbd70.js:40
mc @ index-8c2dbd70.js:38
Ac @ index-8c2dbd70.js:40
kp @ index-8c2dbd70.js:40
zg @ index-8c2dbd70.js:40
bg @ index-8c2dbd70.js:40
sn @ index-8c2dbd70.js:40
Rp @ index-8c2dbd70.js:40
C @ index-8c2dbd70.js:25
tt @ index-8c2dbd70.js:25
Show 1 more frame
index-8c2dbd70.js:73 Uncaught TypeError: Cannot read properties of undefined (reading 'title')
    at hS (index-8c2dbd70.js:73:15705)
    at Qa (index-8c2dbd70.js:38:19479)
    at Bl (index-8c2dbd70.js:40:3134)
    at Pp (index-8c2dbd70.js:40:44559)
    at Tp (index-8c2dbd70.js:40:39572)
    at Vg (index-8c2dbd70.js:40:39500)
    at Pi (index-8c2dbd70.js:40:39355)
    at Ql (index-8c2dbd70.js:40:35752)
    at Rp (index-8c2dbd70.js:40:34708)
    at C (index-8c2dbd70.js:25:1562)
